//
//  test_ssw.cpp
//  iGDA
//
//  Created by Zhixing Feng on 17/11/28.
//  Copyright © 2017年 Zhixing Feng. All rights reserved.
//

#include "../include/catch.hpp"
#include "../include/headers.h"
#include "../src/misc/io.h"
#include "../src/misc/basic.h"
#include "../src/modules/assemble/assembler.h"
#include "../src/modules/alignment/alignment.h"
#include "../tools/tools.h"
#include <ctime>


static void PrintAlignment(const StripedSmithWaterman::Alignment& alignment){
    cout << "===== SSW result =====" << endl;
    cout << "Best Smith-Waterman score:\t" << alignment.sw_score << endl
    << "Next-best Smith-Waterman score:\t" << alignment.sw_score_next_best << endl
    << "Reference start:\t" << alignment.ref_begin << endl
    << "Reference end:\t" << alignment.ref_end << endl
    << "Query start:\t" << alignment.query_begin << endl
    << "Query end:\t" << alignment.query_end << endl
    << "Next-best reference end:\t" << alignment.ref_end_next_best << endl
    << "Number of mismatches:\t" << alignment.mismatches << endl
    << "Cigar: " << alignment.cigar_string << endl;
    cout << "======================" << endl;
}


TEST_CASE("test ssw", "[hide]")
{
    const string query = "AAACCCCGTACCGCCACATCTTCAACAACTGCTGCGCGGCTGTACCGCGTCCTGACGGTGCGCACGCCGAGTTTCTGGTAGAGGTTGCGCGATATGCCGTCTTATGGTGTCGCGCCACCGCCAGTTCGCCGCAATCTGTTCGTTGCTGTACCGAATAGATAAGCCTAACACCTGCCCATTCACGCTGGTGAGCGGGCTGGTGCGAAATAAGCTCCGGGAATCCGGATGGTAAGCAGGCGCTCGGACGAAGCTTCGTCAAAATGGGGCGAATTTATGCGTGATGTTGGTTAATCTCTCCGCAGGATGCCGCTGCGCGCGATGCTGCTCCATCTCCGGCAGCGTATTGAGCTGGGTAAGCTTGACGCAATTGTTGCGCCACTGGCTTCTGCCTTCAATTCACAAAATGGGCTGATAAATCCGGTGCGGTTGCGAAGCTGGTAAGGCATCAAGCAATACGCGCTGGGACGTCGTTTTTTTCCGCCCGATGTGCCAAGTAAAGCTGATGGAGTAACAGCAGATTTGCGGTTAAATCGCTCATTAAGCGCAGCCTACGGCATTCTCATTTAACTCTTCAGCACGATTTCCGCAGGCTCGAATTCGCCCAGCAGGATCTGCGCGCGGCGATATTCCGCATTGCCCTTGCAGAAAATGGTTATTGGCAAACCCCGGTTTTGGGCGTATGACGTAACCAGTTTGCGGCCGGTTTTTTGTCGCCGTTAAATACAGCAACAATCACACCGTAAACTTTATCGCGTTAGAGATTCCAGTCGCAGTGATAACGGCCATTGCCTAATAATTTTTCCAGTCGGTTAAGCTGACTACGGGATTATCCCAGGATCGCCCGCGCGCCGCTGGGCACTGCACCAGTAACGTCAGGCACCGCAAACTGTTGTTTGCGGGGAAGGTGACGCACAGCGATATCGCTGCGCCCGGGACCTCCGCTTCGTTCAAGCGCGCCCACGCCCACAGCAATTGCGCGCGGATTACGTACAGAAACTCATGCATCGGCAGTGTTCCAAGATGCTGCTCCTTTTGATCAATGGAAGGCTCTCTCCTGCGTTTTCCCATGCGGCCTGCAGAATCGCCCTGGCGAACTGAATTTCCGCTTGTTGAATTAAGCTCCA";
    const string ref = "AAACCCCGTACCCCATCATCTTCAGCAACTGCTGCGCGTGCTGTACCGCGTCCTGACGGTGCGCGACGCCGAGTTTCTGGTAGAGGTTGCGGATATGCGTCTTAATGGTGGTCGCGGCCACCGCCAGTTCGCCGGCAATCTGTTCGTTGCTGTAACCGGAATAGATAAGCCCTAACACCTGCCATTCACGCTGGGTGAGCGGGCTGGTGCGAATAAGCTCCGGGACATCCGGATGGTTAAGCAGGCGCTCGACGAAGCCTTCGTCAAAATGGGCGAATTTATGCCGGTGATGTTGGTTAATCTCTCGCAGGATGCGCTGCGCGCGATGCTGCTCCATCTCCGGCAGCGTATTGAGCTGGATAAGCTGACGCAATTGTTGCGCCATGGCTTCGCCTTCAATCACAAAATGGCTGATAAATCCGGTGCGGTTGGCGAGCTGTAAGGCATCAAGCAATACGCGCTGGGCGTCGTTTTTCCGCCCGGATTGCCAGTAAAGCTGATTGAGTAACAGCAGATTGCGGTTTAAATCGCTCATTAAGCGCAGGCTACGGGCATTCTCATTTAACTCTTCCAGCACGATTTCCGCAGGCTCGAATTCGCCCAGCAGGATCTGCGCGCGGGCGATATTCCGCCATTGCCCTTGCAGAAAATGGTTATTGGCAAACGCCGGTTTGGGCGTATGACGTAACCAGTTGGCGGCGGATTTTTTGTCGCCGGTTAACTGCCAGTAAATGACACGCACCTTATCGGCGTTAGAGATCCAGTCGCAGTGATAACGGCCATTGCCTAATAAATTTTCCAGTCGGTTAAGCTGACTACGGGCATTATCCAGATCGCCGCGCGCCAGCGAGCACTGCACCAGTAACGTCAGGCACTGCAACTGTTGTTGCGGCTGGAAGGTGGACAGCACAGCGATACCGCTGCGCGCCGAGGCCTCCGCTTCGTCAAGGCGCGCCCACGCCCACAGCAATTGCGCGCGGATACGTACCAGAAACTCATGCATCGGCAGTTGTTCCAGATGTTGCTCTTTGATCAACTGGAAGGCTCTCTCCTGCGTTTCCCATGCGGCCTGCAGGAATCCCTGGGCGAACTGAATTTCGCTTTGTTGAATTAAGCTCCA";
    int32_t maskLen = (int)strlen(query.c_str())/2;
    //maskLen = maskLen < 15 ? 15 : maskLen;
    maskLen = 1;
    //const string ref   = "CCGTTTATCGCA";
    //const string query = "CCTTTTATCGCA";
    
    // Declares a default Aligner
    StripedSmithWaterman::Aligner aligner(5, 6, 5, 5);

    // Declares a default filter
    StripedSmithWaterman::Filter filter;
    // Declares an alignment that stores the result
    StripedSmithWaterman::Alignment alignment;
    // Aligns the query to the ref
    clock_t time_begin = clock();
    aligner.Align(query.c_str(), ref.c_str(), (int)ref.size(), filter, &alignment, maskLen);
    clock_t time_end = clock();
    cout << "time elapse: " << double(time_end - time_begin) / CLOCKS_PER_SEC << endl;
    PrintAlignment(alignment);

}


TEST_CASE("test Alignment::local_align()", "[hide]")
{
    const string query = "AAACCCCGTACCGCCACATCTTCAACAACTGCTGCGCGGCTGTACCGCGTCCTGACGGTGCGCACGCCGAGTTTCTGGTAGAGGTTGCGCGATATGCCGTCTTATGGTGTCGCGCCACCGCCAGTTCGCCGCAATCTGTTCGTTGCTGTACCGAATAGATAAGCCTAACACCTGCCCATTCACGCTGGTGAGCGGGCTGGTGCGAAATAAGCTCCGGGAATCCGGATGGTAAGCAGGCGCTCGGACGAAGCTTCGTCAAAATGGGGCGAATTTATGCGTGATGTTGGTTAATCTCTCCGCAGGATGCCGCTGCGCGCGATGCTGCTCCATCTCCGGCAGCGTATTGAGCTGGGTAAGCTTGACGCAATTGTTGCGCCACTGGCTTCTGCCTTCAATTCACAAAATGGGCTGATAAATCCGGTGCGGTTGCGAAGCTGGTAAGGCATCAAGCAATACGCGCTGGGACGTCGTTTTTTTCCGCCCGATGTGCCAAGTAAAGCTGATGGAGTAACAGCAGATTTGCGGTTAAATCGCTCATTAAGCGCAGCCTACGGCATTCTCATTTAACTCTTCAGCACGATTTCCGCAGGCTCGAATTCGCCCAGCAGGATCTGCGCGCGGCGATATTCCGCATTGCCCTTGCAGAAAATGGTTATTGGCAAACCCCGGTTTTGGGCGTATGACGTAACCAGTTTGCGGCCGGTTTTTTGTCGCCGTTAAATACAGCAACAATCACACCGTAAACTTTATCGCGTTAGAGATTCCAGTCGCAGTGATAACGGCCATTGCCTAATAATTTTTCCAGTCGGTTAAGCTGACTACGGGATTATCCCAGGATCGCCCGCGCGCCGCTGGGCACTGCACCAGTAACGTCAGGCACCGCAAACTGTTGTTTGCGGGGAAGGTGACGCACAGCGATATCGCTGCGCCCGGGACCTCCGCTTCGTTCAAGCGCGCCCACGCCCACAGCAATTGCGCGCGGATTACGTACAGAAACTCATGCATCGGCAGTGTTCCAAGATGCTGCTCCTTTTGATCAATGGAAGGCTCTCTCCTGCGTTTTCCCATGCGGCCTGCAGAATCGCCCTGGCGAACTGAATTTCCGCTTGTTGAATTAAGCTCCA";
    const string ref = "AAACCCCGTACCCCATCATCTTCAGCAACTGCTGCGCGTGCTGTACCGCGTCCTGACGGTGCGCGACGCCGAGTTTCTGGTAGAGGTTGCGGATATGCGTCTTAATGGTGGTCGCGGCCACCGCCAGTTCGCCGGCAATCTGTTCGTTGCTGTAACCGGAATAGATAAGCCCTAACACCTGCCATTCACGCTGGGTGAGCGGGCTGGTGCGAATAAGCTCCGGGACATCCGGATGGTTAAGCAGGCGCTCGACGAAGCCTTCGTCAAAATGGGCGAATTTATGCCGGTGATGTTGGTTAATCTCTCGCAGGATGCGCTGCGCGCGATGCTGCTCCATCTCCGGCAGCGTATTGAGCTGGATAAGCTGACGCAATTGTTGCGCCATGGCTTCGCCTTCAATCACAAAATGGCTGATAAATCCGGTGCGGTTGGCGAGCTGTAAGGCATCAAGCAATACGCGCTGGGCGTCGTTTTTCCGCCCGGATTGCCAGTAAAGCTGATTGAGTAACAGCAGATTGCGGTTTAAATCGCTCATTAAGCGCAGGCTACGGGCATTCTCATTTAACTCTTCCAGCACGATTTCCGCAGGCTCGAATTCGCCCAGCAGGATCTGCGCGCGGGCGATATTCCGCCATTGCCCTTGCAGAAAATGGTTATTGGCAAACGCCGGTTTGGGCGTATGACGTAACCAGTTGGCGGCGGATTTTTTGTCGCCGGTTAACTGCCAGTAAATGACACGCACCTTATCGGCGTTAGAGATCCAGTCGCAGTGATAACGGCCATTGCCTAATAAATTTTCCAGTCGGTTAAGCTGACTACGGGCATTATCCAGATCGCCGCGCGCCAGCGAGCACTGCACCAGTAACGTCAGGCACTGCAACTGTTGTTGCGGCTGGAAGGTGGACAGCACAGCGATACCGCTGCGCGCCGAGGCCTCCGCTTCGTCAAGGCGCGCCCACGCCCACAGCAATTGCGCGCGGATACGTACCAGAAACTCATGCATCGGCAGTTGTTCCAGATGTTGCTCTTTGATCAACTGGAAGGCTCTCTCCTGCGTTTCCCATGCGGCCTGCAGGAATCCCTGGGCGAACTGAATTTCGCTTTGTTGAATTAAGCTCCA";

    StripedSmithWaterman::Alignment result;
    Alignment aligner;
    aligner.local_align(query, ref, result);
    PrintAlignment(result);
    
}

TEST_CASE(" test seqan global alignment","[hide]")
{
    seqan::String<seqan::Dna5> qseq = "NNNANGNNNNNGGAAACCTGNNNNGN";
    seqan::String<seqan::Dna5> rseq = "GCAACGTCAGGCAGTTCCGACTCTGC";
    
    seqan::Align<seqan::String<seqan::Dna5>, seqan::ArrayGaps> cur_realign;
    seqan::resize(seqan::rows(cur_realign),2);
    seqan::assignSource(seqan::row(cur_realign, 0), qseq);
    seqan::assignSource(seqan::row(cur_realign, 1), rseq);
    
    int gapOpenScore = -4;
    int gapExtendScore = -2;
    
    seqan::Score<int, seqan::ScoreMatrix<seqan::Dna5, seqan::Default> > cur_score(gapExtendScore, gapOpenScore);
    
    for (auto i = 0; i < 4; ++i)
    {
        for (auto j = 0; j < 4; ++j)
        {
            if (i == j)
                setScore(cur_score, seqan::Dna5(i), seqan::Dna5(j), 2);
            else
                setScore(cur_score, seqan::Dna5(i), seqan::Dna5(j), -4);
        }
    }
    for (auto i = 0; i < 5; ++i){
        setScore(cur_score, seqan::Dna5(i), seqan::Dna5(4), 0);
        setScore(cur_score, seqan::Dna5(4), seqan::Dna5(i), 0);
    }
    
    int score = seqan::globalAlignment(cur_realign, cur_score, seqan::AffineGaps());
    
    //int score = seqan::globalAlignment(cur_realign, seqan::Score<int, seqan::Simple>(2, -4, -2, -4), seqan::AffineGaps());
    
    cout << cur_realign << endl;
    cout << seqan::Dna5(0) << endl;
    cout << seqan::Dna5(1) << endl;
    cout << seqan::Dna5(2) << endl;
    cout << seqan::Dna5(3) << endl;
    cout << seqan::Dna5(4) << endl;
}
